### ISSUE TITLE
Misssing close commando's in SimpleDeposit

### ISSUE THREAD

**Issue by niekvanruler** [DANS-KNAW/easy-sword2-dans-examples#15]
in the function:
depositPackage two streams aren't close in:
 // 1. Set up stream for calculating MD5
FileInputStream fis = new FileInputStream(zipFile);
MessageDigest md = MessageDigest.getInstance("MD5");DigestInputStream dis = new DigestInputStream(fis, md);

fis and dis don't have any close commando's

When you try to delete the zip file you get an error: file in use

**Comment by janvanmansum** [comment]
Has been resolved with a [try-with-resources statement](https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html).
